version: '3.8'

services:
  # --- SERVIÇO DE BANCO DE DADOS ---
  db:
    image: postgres:15-alpine
    container_name: crud_postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: crud_api
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- SERVIÇO DA API ---
  api:
    build: .
    container_name: crud_api
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/crud_api?schema=public
      PORT: 3001
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata: