version: '3.8'

services:
  # --- SERVIÇO 1: APLICAÇÃO (API) ---
  api:
    build: .
    container_name: api_container
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgres://user_aula:senha_aula@db:5432/crud_db?schema=public
    depends_on:
      - db
    command: pnpm run dev

  # --- SERVIÇO 2: BANCO DE DADOS ---
  db:
    image: postgres:15-alpine
    container_name: db_container
    restart: always
    environment:
      POSTGRES_USER: user_aula
      POSTGRES_PASSWORD: senha_aula
      POSTGRES_DB: crud_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: